#
###################################
# Site wide configuration
####################################
#
title: Clay McGinnis
email: mcginnis@clay.sh
description: A Programmer and a student at Missouri S&T.
url: # the base hostname & protocol for your site
keywords: ["Programming", "Python", "TypeScript", "JavaScript", "React", "C++", "Programmer", "Golang", "Data", "Education", "Student"]
include: [_redirects]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Chicago
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Clay McGinnis
  avatar: clay.jpg
  job: "Student, Programmer"
  bio: "Student at Missouri S&T. I am proficient in many object oriented languages, and have strong skills in web development, front end and backend."
  email: mcginnis@clay.sh
  disqus-shortname: #username
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: 
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: claymav #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: claymav #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
